# Generated by Django 3.1.7 on 2022-10-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
